### PR TITLE
Code of Conduct file added

### LINKED ISSUE #13: Add CODE_OF_CONDUCT.md
**Is your feature request related to a problem? Please describe.**
No CODE_OF_CONDUCT.md file is present.

**Describe the solution you'd like**
@plxity  As a GSSOC participant I would like to add a CODE_OF_CONDUCT.md file in this project. Using [this]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) as a reference. 

**Additional context**
### Screenshots

code of conduct1
code of conduct2

### PR DESCRIPTION
**Pull request by shreyakapoor08**
FIxes #13 
Added CODE_OF_CONDUCT.md

### CODE REVIEW

**Review by AdityaSrivast — APPROVED** [review]

**Comment by shreyakapoor08** [comment]
@AdityaSrivast Is it fine or any changes are required?

**Comment by AdityaSrivast** [comment]
@shreyakapoor08 do you plan to add more changes in this PR?

**Comment by shreyakapoor08** [comment]
@adityaSrivast it is completed from my side.

**Comment by AdityaSrivast** [comment]
@shreyakapoor08 I have requested review from @plxity and @yellowwoods12 as well. I'd suggest you to keep working on other issues till then

**Review by yellowwoods12 — APPROVED** [review]

**Comment by shreyakapoor08** [comment]
@AdityaSrivast Okay ☺

**Review by plxity — CHANGES_REQUESTED** [review]
@shreyakapoor08 Please add a link of this file in README.md.

**Comment by shreyakapoor08** [comment]
> @shreyakapoor08 Please add a link of this file in README.md.

Done :)

**Review by plxity — APPROVED** [review]

**Pull request merged**
