### PR TITLE
Google Maps feature added

### LINKED ISSUE #21: Addition of Google Maps
**Is your feature request related to a problem? Please describe.**
Google Maps can be added to the existing project for displaying the location of the query.

**Describe the solution you'd like**
A button would pop up on a valid Pincode input, which would redirect to a new webpage (Google Maps) showing the city generated from the query.

**Additional context**
Currently, no Google Maps API will be required.

@plxity  @yellowwoods12 I can work on this. Please assign it to me. Thanks.

### PR DESCRIPTION
**Pull request by adityabisoi**
Closes #21 
A button pops up on a successful query, which redirects to a maps page showing location of the city.

### CODE REVIEW

**Review by yellowwoods12 — COMMENTED** [review]
Implementation is fine but the requirement of this is not clear to me. @plxity  Have a look.

**Comment by plxity** [comment]
@yellowwoods12 I have merged its implementation on the original module in some different branch but we are not sure if we need this feature. So we have to keep this on hold.

**Comment by adityabisoi** [comment]
@plxity I had already implemented it on the website. Should I remove the implementation?

**Comment by plxity** [comment]
Yes, please remove that.

**Comment by adityabisoi** [comment]
@plxity Done

**Pull request closed without merging**
